{% set name = "yen" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/yen-{{ version }}.tar.gz
  sha256: 9ecff428998b6ba7ca2ae4d8ef3350ac8d2031b60a66c38d7863bbad4ba9ef37

build:
  entry_points:
    - yen=yen.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - microvenv >=2023.2.0
    - rich >=13.5.3

test:
  imports:
    - yen
  commands:
    - pip check
    - yen --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tusharsadhwani/yen
  summary: Yet another Python environment manager.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
