{% set name = "yen" %}
{% set version = "0.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/yen-{{ version }}.tar.gz
  sha256: 1cae75c74d628c8f28cb599b96eb30d0c8d16a612a8ad31fd1d5b5e4b2102b99

build:
  entry_points:
    - yen=yen.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - microvenv >=2023.2.0
    - rich >=13.5.3

test:
  imports:
    - yen
  commands:
    - pip check
    - yen --help
  requires:
    - pip

about:
  home: https://github.com/tusharsadhwani/yen
  summary: Yet another Python environment manager.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
